### ISSUE TITLE
Null pointer exception at InfoCert 

### ISSUE THREAD

**Issue by maazmmd** [jocker2206/node-signature#1]
Exception in thread "main" java.lang.NullPointerException
	at signature.InfoCert.<init>(InfoCert.java:81)
	at signature.Sign.signing(Sign.java:97)
	at signature.Signature.main(Signature.java:67)

Am using a X.509 certificate and passing the pfx file and pdf but I get a Null pointer exception. Kindly help me out with this issue

**Comment by maazmmd** [comment]
Unable to access Signer, as the files are present in the src folder, it should be renamed to the lib folder

Issues in the jar (Java files)
1. Unable to reposition the digital signature, as there are no additional parameters in Signature.java file (being run) from the command line 
2. jar file doesn't execute the digital signature as Invalid parameters for the method createSIgnature

**Comment by jocker2206** [comment]
Hola, quiero ayudarte con tu problema.Puedes mándame un pantallazo o parte de tu código donde se genera el error para poder corregirlo. Muchas gracias de antemano  Enviado desde Correo para Windows 10 De: Mohammed MaazEnviado: martes, 27 de octubre de 2020 00:28Para: jocker2206/node-signatureCC: SubscribedAsunto: Re: [jocker2206/node-signature] Null pointer exception at InfoCert (#1) Unable to access Signer, as the file are present in the src folder, it should be renamed to lib folder—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by maazmmd** [comment]
Hi,

Hope you are doing well, I apologize for the late reply. Please find
attached issues or enhancements needed as stated below,

Issues :
1. The Jar file has hardcoded Spanish in Method, which cannot be used by
everyone

setLayer2Text() method


2. Importing Signer in Node doesn't seem to work
We need to do it this way
const Signer = require('../node_modules/node-signature/src/Signer');

3. Few code changes for Signer.js

let command = `java -jar "${jar}"
"PFX=${pfx};PASSPFX=${passPfx};SOURCE=${source};TARGET=${target}`;

// To be added after for loop

command += `"`; // This line needs to added after for loop as the Java
command seems to fail

// Adding few extra enhancements

marginLeft: "415.0F",
marginBottom: "180.0F" // To be added in defaultOptions for
dynamically changing the Digital signature location

Enhancements:
1. for fields like Location, Date options, digitally signature location on
the page(already present in Signer.js) should be provided dynamically.
For Java code changes please refer my github repo (
https://github.com/maazmmd/digital-sign-pdf.git)

Please feel free to reach out to me, I would be more than happy to
contribute. I made changes locally and made it work.
Thank you.

Best Regards,
Maaz
